### ISSUE TITLE
Body Shadow (except arms) Disappear in First Person

### ISSUE THREAD

**Issue by Corruptikoo** [duke-tylerjone/gc-bugs-and-feedback#12]
Third Person Screenshot
![image](https://user-images.githubusercontent.com/67384882/85920962-ebe7a780-b8aa-11ea-8cf1-96b21970d944.png)

First Person Screenshot
![image](https://user-images.githubusercontent.com/67384882/85920973-00c43b00-b8ab-11ea-9242-afe2eb6545d5.png)

**Comment by LoreDreamer** [comment]
That certainly is a pickle.

Anyhow, did you notice that in third person you can see your whole self meanwhile in first person you can only see your arms? Maybe it's something related to that, as the shadows are local. When you're in third person you see yourself entirely, meaning the whole shadow will show.

Meanwhile, when you're in first person you only see the shadow of your arms because you only see them in first person.

**Comment by duke-tylerjone** [comment]
Unfortunately, as @LoreDreamer explained partially, it's because the torso and legs are transparent locally. Therefore, it doesn't render shadows because technically the object is invisible.
